### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by chrisbolin** [FormidableLabs/victory-docs#364]
## Issue 

3 consistent errors in our travis builds for the past two weeks: `npm run test-func-static-prod`
```
  1) Playgrounds should render:
      AssertionError: expected false to equal true
      + expected - actual
      -false
      +true
      
      at Object.<anonymous> (test/func/spec/playgrounds.spec.js:17:41)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:538:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
  2) Sidebar search should filter sidebar to matching content and their parents:
     AssertionError: expected [ Array(3) ] to deeply equal 'Documentation'
      at elementIdText("4514") - getText.js:35:50
  3) Sidebar search should render toc that match search input:
     Error: An element could not be located on the page using the given search parameters (".Sidebar-toc-item a").
      at execute(<Function>) - selectorExecute.js:58:65
      at execute("return !!document.evaluate;") - ensureClientSideSelectorSupport.js:23:17
```

## Local Testing steps

```sh
# Install, build
$ npm install
$ builder run install-selenium
$ NODE_ENV=production builder run build-static

# Test in browsers
$ ROWDY_SETTINGS="local.chrome" builder run test-func-static # => PASSES
$ ROWDY_SETTINGS="local.phantomjs" builder run test-func-static # => FAILS LIKE TRAVIS
```

**Comment by chrisbolin** [comment]
The two Sidebar issues ostensibly have the same root cause: the sidebar filtering doesn't appear work in the test (but it does work in all manually tests).

`.setValue(".Input-search", "victorya")` appears to set the value correctly (i.e. `.getValue` confirms it), but the same headings appear as before `.setValue` is called.

**Comment by chrisbolin** [comment]
I am 99% sure this is a **dependency issue**: I just reran the Travis tests for `victory-docs@v4.3.1` which **passed** when run two weeks ago, and they now fail. Most likely this is because different dependencies were installed.

```
  1) Playgrounds should render:
     Error: element (".Interactive > .playground") still not existing after 20000ms
      at elements(".Interactive > .playground") - isExisting.js:46:17
      at isExisting(".Interactive > .playground") - waitForExist.js:67:22
  2) Playgrounds should reflect changes:
     Error: element (".Interactive > .playground") still not existing after 20000ms
      at elements(".Interactive > .playground") - isExisting.js:46:17
      at isExisting(".Interactive > .playground") - waitForExist.js:67:22
  3) Sidebar search should filter sidebar to matching content and their parents:
     AssertionError: expected [ Array(3) ] to deeply equal 'Documentation'
      at elementIdText("4321") - getText.js:35:50
  4) Sidebar search should render toc that match search input:
     Error: An element could not be located on the page using the given search parameters (".Sidebar-toc-item a").
      at elements(".Sidebar-toc-item a") - getText.js:18:17
      at elementIdValue("4322", "victoryarea styl") - setValue.js:46:80
```

(The "extra" test failure here is probably a consequence of changing the test since then.)

**Comment by chrisbolin** [comment]
because Travis throws away old runs of the exact same job, I used the two jobs per PR as a test. We seem the same behavior here, even though the *exact same code* is used. It must be underlying dependencies then.

[Build #458](https://travis-ci.org/FormidableLabs/victory-docs/builds/238491329)

2017-06-01 job [#458.1 - Passes](https://travis-ci.org/FormidableLabs/victory-docs/jobs/238491330)
2017-06-23 job [#458.2 - Fails](https://travis-ci.org/FormidableLabs/victory-docs/jobs/238491331)

This should provide a nice place to look at dependency changes.

**Comment by chrisbolin** [comment]
I can't find anything :/ 

sanitized npm diff...
```
A babel-template@6.24.1
B babel-template@6.25.0
A babel-generator@6.24.1
B babel-generator@6.25.0
A babel-core@6.24.1
B babel-core@6.25.0
A babel-traverse@6.24.1
B babel-traverse@6.25.0
A globals@9.17.0
B globals@9.18.0
A babel-types@6.24.1
B babel-types@6.25.0
A babylon@6.17.2
B babylon@6.17.4
A brace-expansion@1.1.7
B brace-expansion@1.1.8
A babel-plugin-transform-react-display-name@6.23.0
B babel-plugin-transform-react-display-name@6.25.0
A coa@1.0.2
B coa@1.0.3
A clap@1.1.3
B clap@1.2.0
A postcss@6.0.1
B postcss@6.0.2
A uglify-js@2.8.27
B uglify-js@2.8.29
A readable-stream@2.2.9
A buffer-shims@1.0.0
B readable-stream@2.3.2
A string_decoder@1.0.1
B string_decoder@1.0.3
A nwmatcher@1.4.0
B nwmatcher@1.4.1
A sshpk@1.13.0
B sshpk@1.13.1
A jodid25519@1.0.2
B safe-buffer@5.1.1
A uuid@3.0.1
B uuid@3.1.0
A sax@1.2.2
B sax@1.2.4
A electron-to-chromium@1.3.13
A caniuse-db@1.0.30000676
B electron-to-chromium@1.3.14
B caniuse-db@1.0.30000693
B balanced-match@0.4.2
B balanced-match@0.4.2
A postcss-custom-properties@5.0.2
B postcss-custom-properties@5.0.2
B balanced-match@0.4.2
A postcss-image-set-polyfill@0.3.4
A postcss@6.0.1
B postcss-image-set-polyfill@0.3.5
B postcss@6.0.2
A postcss-selector-matches@2.0.5
B postcss-selector-matches@2.0.5
B balanced-match@0.4.2
A jspm@0.17.0-beta.41
B jspm@0.17.0-beta.42
A   tar-fs@1.15.2
B   tar-fs@1.15.3
A    global-prefix@0.1.5
A    homedir-polyfill@1.0.1
A    parse-passwd@1.0.0
B    global-prefix@0.1.5
A   fined@1.0.2
A   lodash.assignwith@4.2.0
A   lodash.isempty@4.4.0
A   lodash.pick@4.4.0
B   fined@1.1.0
B   expand-tilde@2.0.2
B   homedir-polyfill@1.0.1
B   parse-passwd@1.0.0
B   is-plain-object@2.0.3
B   isobject@3.0.0
B   object.defaults@1.1.0
B   array-each@1.0.1
B   array-slice@1.0.0
B   for-own@1.0.0
B   isobject@3.0.0
B   object.pick@1.2.0
B   isobject@2.1.0
A   systemjs@0.20.10
A   systemjs-builder@0.16.4
A   babel-core@6.24.1
B   systemjs@0.20.14
B   systemjs-builder@0.16.9
B   babel-core@6.25.0
A base64-js@1.2.0
B base64-js@1.2.1
A stream-http@2.7.1
B stream-http@2.7.2
A es5-ext@0.10.22
B es5-ext@0.10.23
A esrecurse@4.1.0
A estraverse@4.1.1
B esrecurse@4.2.0
B estraverse@4.2.0
A commander@2.9.0
B commander@2.10.0
A uuid@3.0.1
B uuid@3.1.0
A commander@2.9.0
B commander@2.10.0
A uuid@3.0.1
B uuid@3.1.0
A remove-trailing-separator@1.0.1
B remove-trailing-separator@1.0.2
A zip-stream@1.1.1
B zip-stream@1.2.0
A globule@1.1.0
B globule@1.2.0
A   lodash@4.16.6
A iconv-lite@0.4.17
B iconv-lite@0.4.18
A   webpack-dev-middleware@1.10.2
B   webpack-dev-middleware@1.11.0
A babel-core@6.24.1
B babel-core@6.25.0
A isobject@2.1.0
A   randomatic@1.1.6
B randomatic@1.1.7
B   is-number@3.0.0
B kind-of@3.2.2
B kind-of@4.0.0
A babel-core@6.24.1
B babel-core@6.25.0
A babel-standalone@6.24.2
A codemirror@5.26.0
B babel-standalone@6.25.0
B codemirror@5.27.2
A url-loader@0.5.8
B url-loader@0.5.9
A babel-core@6.24.1
B babel-core@6.25.0
A mobx@3.1.11
B mobx@3.1.16
A babel-core@6.24.1
B babel-core@6.25.0
A react@15.5.4
B react@15.6.1
B create-react-class@15.6.0
A node-fetch@1.7.0
B node-fetch@1.7.1
A promise@7.1.1
B promise@7.3.1
A ua-parser-js@0.7.12
B ua-parser-js@0.7.13
A react-addons-test-utils@15.5.1
B react-addons-test-utils@15.6.0
A react-dom@15.5.4
A react-ga@2.2.0
A └── create-react-class@15.5.3
B react-dom@15.6.1
B react-ga@2.2.0
A sinon-chai@2.10.0
B sinon-chai@2.11.0
A d3-collection@1.0.3
B d3-collection@1.0.4
A d3-time@1.0.6
B d3-time@1.0.7
A d3-timer@1.0.5
B d3-timer@1.0.6
```

**Comment by chrisbolin** [comment]
very significant versions that *didn't change*:
- webdriverio@4.8.0
- selenium-standalone@5.11.2

could be a change with react / react-dom:
- react@15.5.4 -> react@15.6.1
- react-dom@15.5.4 -> react-dom@15.6.1

**Comment by chrisbolin** [comment]
#365 by @ryan-roemer fixes this by using headless Chrome rather than PhantomJS.

What likely happened was this...
- PhantomJS was correctly running our JavaScript build circa June 1.
- Some transitive dependency released a patch or minor upgrade that _broke on phantom_ but not "real" browsers like Chrome, Firefox, Safari.
- Travis and _new_ local npm installs started picking up that dependency 
- Any tests that actually relied on JS broke. Because Victory Docs is a static site, very few of our tests broke, only 4 out of 75. The four failing tests involved the sidebar filter and the playground.

**Comment by chrisbolin** [comment]
Next steps:
- -Use Chrome instead of PhantomJS in CI- DONE in #365
- Use Chrome instead of PhantomJS locally
- Use yarn so that we can be intentional about transitive dependency changes
- Check committed changes to the tests in the last two weeks to make sure we didn't change something we didn't need to

**Comment by chrisbolin** [comment]
alright, build passes and we are more prepared and document. closing
